### PR TITLE
Standarized command output

### PR DESCRIPTION
**Pull request by Hajto**
If you like this idea, comment then I'll update `Readme.md`

### CODE REVIEW

**Comment by asiniy** [comment]
Each `ecto` method for changeset manipulation takes a changeset and returns a changeset, not a tuple. It's not a repo level function (which are behave exactly like this)
So, thanks, but no

**Comment by Hajto** [comment]
So maybe introduce new function type? They are very usefull for ROP

**Comment by asiniy** [comment]
ROP? What is that?

**Comment by Hajto** [comment]
Rail oriented programming. Basically a simplified Try monad or a universal plug if you will.

If functions `f1`, `f2`,`f3` all return either `{ok, v}` or `{error, why}` then following expression:

```
result = 
  args
  |> f1
  >>> f2
  >>> f3
```

if f1 return ok than value gets unpacked and passed to f2 else return error and so forth and so on.

Here is a sample implementation: https://github.com/ruby2elixir/rop
I prefer to use some more customized version of my own.

Having a function that returns standarized input also eases usage with `with` construct from Elixir.

**Comment by asiniy** [comment]
I'm using `with` elixir statement for that. Work with it maybe?

As I see at `ruby2elixir` repo, nobody uses rop

**Pull request closed without merging**
